# Generated by Django 4.2.10 on 2024-03-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99, verbose_name='Название баннера')),
                ('link', models.CharField(max_length=300, verbose_name='Ссылка')),
                ('photo', models.ImageField(blank=True, upload_to='banners/%Y/%m/%d', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Баннеры на главной странице',
                'verbose_name_plural': 'Баннеры на главной странице',
                'ordering': ['-created_at'],
            },
        ),
    ]
