# Generated by Django 4.2.10 on 2024-05-03 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_category_common_type_category'),
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='description',
            field=models.CharField(default=1, max_length=1000, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banners',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_banner', to='products.shop', verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='title',
            field=models.CharField(max_length=99, verbose_name='Название акции'),
        ),
    ]
