# Generated by Django 4.2.10 on 2024-05-11 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_city_zoom'),
        ('banners', '0002_banners_description_banners_shop_alter_banners_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_city', to='products.city', verbose_name='Город'),
        ),
    ]
