# Generated by Django 4.2.10 on 2024-07-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_banners_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='deadline_date',
            field=models.DateField(auto_now=True, verbose_name='Дата окончания акции'),
        ),
    ]
