# Generated by Django 4.2.10 on 2024-07-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_banners_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='deadline_date',
            field=models.DateField(verbose_name='Дата окончания акции'),
        ),
    ]
