# Generated by Django 4.2.10 on 2024-08-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0006_alter_banners_deadline_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='photo',
            field=models.ImageField(blank=True, upload_to='prbn/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
