# Generated by Django 4.2.10 on 2025-01-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0007_alter_banners_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='sorting_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Порядок сортировки'),
        ),
    ]
