# Generated by Django 4.2.10 on 2024-07-12 15:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0025_shop_tiktok_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=99, null=True, verbose_name='ФИО')),
                ('label', models.CharField(default='', max_length=99, verbose_name='Надпись')),
                ('description', models.TextField(max_length=500, verbose_name='Отзыв')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('grade', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='Оценка')),
                ('shop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_reviews', to='products.shop', verbose_name='Торговая точка')),
            ],
            options={
                'verbose_name': 'Отзывы по торговым точкам',
                'verbose_name_plural': 'Отзывы по торговым точкам',
                'ordering': ['-created_at'],
            },
        ),
    ]
