# Generated by Django 4.2.10 on 2024-07-12 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewsshop',
            name='label',
        ),
    ]
