# Generated by Django 4.2.10 on 2024-08-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_shop', '0002_remove_reviewsshop_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsshop',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/reviews_shop/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='reviewsshop',
            name='telephone',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='reviewsshop',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Отзыв'),
        ),
    ]
