# Generated by Django 4.2.10 on 2024-05-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviews_options_alter_reviews_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='label',
            field=models.CharField(default='', max_length=99, verbose_name='Надпись'),
        ),
    ]
