# Generated by Django 4.2.10 on 2024-05-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_main', models.CharField(max_length=80, verbose_name='Надпись на главной странице')),
                ('label_info_title', models.CharField(max_length=100, verbose_name='Название в блоке информации')),
                ('label_info_desc', models.CharField(max_length=100, verbose_name='Описание в блоке информации')),
                ('photo_info', models.ImageField(blank=True, upload_to='other/mainpage/%Y/%m/%d', verbose_name='Изображение большое')),
                ('label_info_1', models.CharField(max_length=100, verbose_name='Напись первого блока')),
                ('label_info_1_desc', models.CharField(max_length=100, verbose_name='Напись первого блока')),
                ('photo_info_1', models.ImageField(blank=True, upload_to='other/mainpage/%Y/%m/%d', verbose_name='Изображение первого блока')),
                ('label_info_2', models.CharField(max_length=100, verbose_name='Напись второго блока')),
                ('label_info_2_desc', models.CharField(max_length=100, verbose_name='Напись второго блока')),
                ('photo_info_2', models.ImageField(blank=True, upload_to='other/mainpage/%Y/%m/%d', verbose_name='Изображение второго блока')),
                ('label_info_3', models.CharField(max_length=100, verbose_name='Напись третьего блока')),
                ('label_info_3_desc', models.CharField(max_length=100, verbose_name='Напись третьего блока')),
                ('photo_info_3', models.ImageField(blank=True, upload_to='other/mainpage/%Y/%m/%d', verbose_name='Изображение третьего блока')),
                ('label_author', models.CharField(max_length=100, verbose_name='Напись третьего блока')),
                ('label_author_desc', models.CharField(max_length=100, verbose_name='Напись третьего блока')),
                ('photo_author', models.ImageField(blank=True, upload_to='other/mainpage/%Y/%m/%d', verbose_name='Изображение третьего блока')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Блок на главной странице',
                'verbose_name_plural': 'Блок на главной странице',
            },
        ),
    ]
