# Generated by Django 4.2.10 on 2024-05-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageinfo',
            name='label_author',
            field=models.CharField(max_length=200, verbose_name='Напись третьего блока'),
        ),
        migrations.AlterField(
            model_name='mainpageinfo',
            name='label_author_desc',
            field=models.CharField(max_length=200, verbose_name='Напись третьего блока'),
        ),
        migrations.AlterField(
            model_name='mainpageinfo',
            name='label_info_1',
            field=models.CharField(max_length=200, verbose_name='Напись первого блока'),
        ),
        migrations.AlterField(
            model_name='mainpageinfo',
            name='label_info_1_desc',
            field=models.CharField(max_length=200, verbose_name='Напись первого блока'),
        ),
        migrations.AlterField(
            model_name='mainpageinfo',
            name='label_info_2',
            field=models.CharField(max_length=200, verbose_name='Напись второго блока'),
        ),
        migrations.AlterField(
            model_name='mainpageinfo',
            name='label_info_2_desc',
            field=models.CharField(max_length=200, verbose_name='Напись второго блока'),
        ),
        migrations.AlterField(
            model_name='mainpageinfo',
            name='label_info_3',
            field=models.CharField(max_length=200, verbose_name='Напись третьего блока'),
        ),
        migrations.AlterField(
            model_name='mainpageinfo',
            name='label_info_3_desc',
            field=models.CharField(max_length=200, verbose_name='Напись третьего блока'),
        ),
        migrations.AlterField(
            model_name='mainpageinfo',
            name='label_info_desc',
            field=models.CharField(max_length=200, verbose_name='Описание в блоке информации'),
        ),
        migrations.AlterField(
            model_name='mainpageinfo',
            name='label_info_title',
            field=models.CharField(max_length=200, verbose_name='Название в блоке информации'),
        ),
    ]
