# Generated by Django 4.2.10 on 2024-05-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_alter_mainpageinfo_label_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpageinfo',
            name='label_main',
        ),
    ]
