# Generated by Django 4.2.10 on 2024-05-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0003_remove_mainpageinfo_label_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageinfo',
            name='label_author',
            field=models.CharField(max_length=200, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='mainpageinfo',
            name='label_author_desc',
            field=models.CharField(max_length=200, verbose_name='Описание автора'),
        ),
        migrations.AlterField(
            model_name='mainpageinfo',
            name='label_info_1_desc',
            field=models.CharField(max_length=200, verbose_name='Описание первого блока'),
        ),
        migrations.AlterField(
            model_name='mainpageinfo',
            name='label_info_2_desc',
            field=models.CharField(max_length=200, verbose_name='Описание второго блока'),
        ),
        migrations.AlterField(
            model_name='mainpageinfo',
            name='label_info_3_desc',
            field=models.CharField(max_length=200, verbose_name='Описание третьего блока'),
        ),
        migrations.AlterField(
            model_name='mainpageinfo',
            name='photo_author',
            field=models.ImageField(blank=True, upload_to='other/mainpage/%Y/%m/%d', verbose_name='Изображение автора'),
        ),
    ]
