# Generated by Django 4.2.10 on 2024-05-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0004_alter_mainpageinfo_label_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Подпись')),
                ('title', models.CharField(max_length=200, verbose_name='Надпись')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('button_label', models.CharField(max_length=200, verbose_name='Текст кнопки')),
                ('link', models.CharField(max_length=500, verbose_name='Ссылка')),
                ('label_info_title', models.CharField(max_length=200, verbose_name='Название в блоке информации')),
                ('photo', models.ImageField(blank=True, upload_to='other/mainpage/%Y/%m/%d', verbose_name='Изображение на фон')),
            ],
            options={
                'verbose_name': 'Акция на главной странице',
                'verbose_name_plural': 'Акция на главной странице',
            },
        ),
    ]
