# Generated by Django 4.2.10 on 2024-05-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0005_mainpagesale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpagesale',
            name='label_info_title',
        ),
        migrations.AlterField(
            model_name='mainpagesale',
            name='button_label',
            field=models.CharField(max_length=20, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='mainpagesale',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
    ]
