# Generated by Django 4.2.10 on 2024-07-12 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0025_shop_tiktok_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopViewStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(db_index=True, max_length=100, verbose_name='IP клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('shop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_statistics', to='products.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Статистика по ресторану',
                'verbose_name_plural': 'Статистика по ресторану',
                'ordering': ['shop'],
            },
        ),
        migrations.CreateModel(
            name='ProductViewStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ip', models.CharField(db_index=True, max_length=100, verbose_name='IP клиента')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_statistics', to='products.products', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Статистика по продуктам',
                'verbose_name_plural': 'Статистика по продуктам',
                'ordering': ['product'],
            },
        ),
    ]
