# Generated by Django 4.2.10 on 2024-07-12 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_shop_tiktok_login'),
        ('statistics_gau', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productviewstatistics',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_statistics', to='products.products', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='shopviewstatistics',
            name='shop',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_statistics', to='products.shop', verbose_name='Торговая точка'),
        ),
    ]
