# Generated by Django 4.2.10 on 2024-03-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_country_city_shop_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='address',
            field=models.CharField(default=1, max_length=2000, verbose_name='Адрес магазина'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Рейтинг магазина'),
        ),
    ]
