# Generated by Django 4.2.10 on 2024-03-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_products_address_shop_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='workTime',
            field=models.CharField(default=1, max_length=99, verbose_name='Режим работы магазина'),
            preserve_default=False,
        ),
    ]
