# Generated by Django 4.2.10 on 2024-03-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_shop_worktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='phoneNumber',
            field=models.CharField(default=1, max_length=99, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
