# Generated by Django 4.2.10 on 2024-03-02 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=99, verbose_name='Название статуса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Статус магазина',
                'verbose_name_plural': 'Статус магазина',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='productprice',
            name='new_price',
            field=models.FloatField(default=0, verbose_name='Новая цена на товар'),
        ),
        # migrations.AddField(
        #     model_name='shop',
        #     name='premium_status',
        #     field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='get_shop_status', to='products.premiumstatus', verbose_name='Статус магазина'),
        #     preserve_default=False,
        # ),
    ]
