# Generated by Django 4.2.10 on 2024-03-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_premiumstatus_productprice_new_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='premium_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_shop_status', to='products.premiumstatus', verbose_name='Статус магазина'),
        ),
    ]
