# Generated by Django 4.2.10 on 2024-03-09 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_shop_premium_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Тип тороговой точки')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Тип торговой точки',
                'verbose_name_plural': 'Тип торговой точки',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TypeOfShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Тип тороговой точки')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Тип торговой точки',
                'verbose_name_plural': 'Тип торговой точки',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['-created_at'], 'verbose_name': 'Торговая точка', 'verbose_name_plural': 'Торговая точка'},
        ),
        migrations.AlterField(
            model_name='productprice',
            name='new_price',
            field=models.FloatField(default=0, verbose_name='Старая цена на товар'),
        ),
        migrations.AddField(
            model_name='shop',
            name='generalType',
            field=models.ManyToManyField(blank=True, related_name='get_general_type_of_shop', to='products.generalcategories', verbose_name='Тип торговой точки'),
        ),
        migrations.AddField(
            model_name='shop',
            name='typeOfShop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_type_of_shop', to='products.typeofshop', verbose_name='Тип торговой точки'),
        ),
    ]
