# Generated by Django 4.2.10 on 2024-03-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_generalcategories_typeofshop_alter_shop_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Вид доставки')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Вид доставки',
                'verbose_name_plural': 'Вид доставки',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='generalcategories',
            options={'ordering': ['title'], 'verbose_name': 'Общая категория', 'verbose_name_plural': 'Общая категория'},
        ),
        migrations.AlterField(
            model_name='shop',
            name='generalType',
            field=models.ManyToManyField(blank=True, related_name='get_general_type_of_shop', to='products.generalcategories', verbose_name='Общие категории'),
        ),
        migrations.AddField(
            model_name='shop',
            name='deliveryType',
            field=models.ManyToManyField(blank=True, related_name='get_delivery_type_of_shop', to='products.deliverytype', verbose_name='Методы доставки'),
        ),
    ]
