# Generated by Django 4.2.10 on 2024-03-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_deliverytype_alter_generalcategories_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralCategoriesOfProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Общая категория товара')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Общая категория товара',
                'verbose_name_plural': 'Общая категория товара',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='generalcategories',
            options={'ordering': ['title'], 'verbose_name': 'Общая категория торговой точки', 'verbose_name_plural': 'Общая категория торговой точки'},
        ),
        migrations.AlterField(
            model_name='generalcategories',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Общая категория торговой точки'),
        ),
    ]
