# Generated by Django 4.2.10 on 2024-03-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_generalcategoriesofproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='generalType',
            field=models.ManyToManyField(blank=True, related_name='get_general_type_of_shop', to='products.generalcategoriesofproduct', verbose_name='Общие категории'),
        ),
    ]
