# Generated by Django 4.2.10 on 2024-03-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_products_generaltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Название атрибута')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Дополнительные атрибуты',
                'verbose_name_plural': 'Дополнительные атрибуты',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='shop',
            name='additionalAttributes',
            field=models.ManyToManyField(blank=True, related_name='get_additional_attributes_of_shop', to='products.additionalattributes', verbose_name='Дополнительные атрибуты'),
        ),
    ]
