# Generated by Django 4.2.10 on 2024-04-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_additionalattributes_shop_additionalattributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonTypeOfCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='slug')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Группировка категорий',
                'verbose_name_plural': 'Группировка категорий',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='products',
            name='carbs',
            field=models.FloatField(default=0, null=True, verbose_name='Углеводы'),
        ),
        migrations.AddField(
            model_name='products',
            name='fat',
            field=models.FloatField(default=0, null=True, verbose_name='Жир'),
        ),
        migrations.AddField(
            model_name='products',
            name='protein',
            field=models.FloatField(default=0, null=True, verbose_name='Белки'),
        ),
        migrations.AddField(
            model_name='products',
            name='show_calories',
            field=models.BooleanField(default=False, verbose_name='Показывать БЖУ'),
        ),
    ]
