# Generated by Django 4.2.10 on 2024-04-18 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_commontypeofcategory_products_carbs_products_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='common_type_category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='get_common_category', to='products.commontypeofcategory', verbose_name='Группировка категорий'),
            preserve_default=False,
        ),
    ]
