# Generated by Django 4.2.10 on 2024-04-18 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_category_common_type_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='common_type_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='get_common_category', to='products.commontypeofcategory', verbose_name='Группировка категорий'),
        ),
    ]
