# Generated by Django 4.2.10 on 2024-05-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_shop_sorting_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='zoom',
            field=models.IntegerField(blank=True, default=12, verbose_name='Зум'),
        ),
    ]
