# Generated by Django 4.2.10 on 2024-07-01 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_city_zoom'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop_images/%Y/%m/%d', verbose_name='Изображение')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.shop')),
            ],
            options={
                'verbose_name': 'Изображение магазина',
                'verbose_name_plural': 'Изображения магазина',
            },
        ),
    ]
