# Generated by Django 4.2.10 on 2024-07-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_shopimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='instagram_login',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram Логин'),
        ),
        migrations.AddField(
            model_name='shop',
            name='web_site',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на сайт'),
        ),
        migrations.AddField(
            model_name='shop',
            name='youtube_src',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на Youtube'),
        ),
    ]
