# Generated by Django 4.2.10 on 2024-08-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_shop_tiktok_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Адрес магазина'),
        ),
    ]
