# Generated by Django 4.2.10 on 2025-02-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_shop_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_value', models.CharField(choices=[('oraza', 'Oraza')], default='oraza', max_length=64, verbose_name='Вид меню')),
                ('title', models.CharField(blank=True, max_length=99, null=True, verbose_name='Название магазина')),
                ('description', models.TextField(max_length=500, verbose_name='Содержание меню')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('shop', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='select_special_shop', to='products.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Специальное меню',
                'verbose_name_plural': 'Специальное меню',
                'ordering': ['-created_at'],
            },
        ),
    ]
