# Generated by Django 4.2.10 on 2025-02-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_specialmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialmenu',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания меню'),
        ),
        migrations.AlterField(
            model_name='specialmenu',
            name='title',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Название меню'),
        ),
    ]
